### ISSUE TITLE
REQUEST: Time Tracking Tweek + Project Groups + Task Editing

### ISSUE THREAD

**Issue by treblesand** [gelform/kanban#23]
I LOVE the fact that we can track how much time is spent on a task.  However, not all tasks are going to take an hour to complete.  Or maybe they take 2 1/2 hrs.  It would be great if the admin could set the increment that best fits the particular application of this plug in.  For example, I might want to set it to 10 min, or minute by minute.  Someone else might want 1/2 hour.  
In my instance, we charge a minimum of 10 minutes of our time for each task we complete for a client.  Sometimes these tasks are simple and take less than 10 minutes or maybe they take 20 minutes. 

Project Groups:
I can foresee the project selection spot getting crazy, if there are a LOT of projects to choose from.  Being able to group them would be a great way to fix that, and increase efficiency.  For example, perhaps someone has a client for whom they do several different projects.  Or perhaps a huge project has segments to it (a website for example might have "Graphic Design", "Coding", "testing" etc as project headings with individual tasks for each?)  Maybe this is something you address already?  

Task editing: I'd LOVE to be able to get to an editing screen for each task from the board.  Perhaps clicking on the task number could show MORE than just the option to delete.  More likely there should be a menu icon to the left or right of the task number (Is the task number important to see?) allowing us to delete, edit, add a to-do list perhaps under each task so someone working on it could check off each thing they've done?  Assign a task to more than one person?

Thank you for hearing all this stuff!  I hope this all helps and I look forward to continuing the tests.

**Comment by treblesand** [comment]
You might hate me by the time this is done... ;)

Another idea that would be really helpful is to have project statuses... to help keep track of a project that's in negotiation, one that's contracted and ready to start, maybe at different phases, final review, completed etc.

**Comment by gelform** [comment]
No way! I love any and all ideas!

Task time: I'll look at adding a setting for the minimum time interval e.g. .16 = 10 minutes

Project groups: This was why I made projects a post type. I expect there will have to be a fair amount of creating and deleting projects. In the future I will add a search to the dropdown, and only show recently used projects in the top 10. But since it's a post type, it could have a hierarchy, so conceivably there could be sub-menus. I'll have to look into that.

Task editing: The goal is to be able to edit anything about a task from the task itself. (you can click on the task title to edit it, for example). We're talking about sub-tasks as an add-on. What other options would you want to see?

Project status: interesting idea. Sounds like a different screen to me. I don't see how it would fit into the current board, especially since I'm trying to adhere "strictly" to the Kanban model. We're talking about multiple boards as an add-on, so maybe you have another board to track project statuses?

Keep the ideas coming!
