### ISSUE TITLE
No uninstall file

### ISSUE THREAD

**Issue by wpsmith** [gelform/kanban#6]

**Comment by gelform** [comment]
Should I still have an uninstall file, if there's nothing I want to uninstall?

**Comment by mkrdip** [comment]
Hi @wpsmith, 

Adding few lines of descriptions to issues could be a great help for the developers to identify facts. 

Hi @gelform, 

In most situations that the core WordPress uninstall.php functionality should be used for uninstall situations involving plugins.

However, with Kanban for WordPress we might need to have our own uninstall process and implementation. Because of the fact our plugin is commonly used for information that is considered critical and vital to a team, the accidental deletion of it is something they want to avoid.

Some users are dumb. They may not realize “Uninstall” means they would lose ALL of their data. They may use it when they are simply playing around with their site and removing and adding a different version of the plugin, etc. not realizing the implications. They may not realizing that by “deleting” a plugin it’s going to delete ALL of the data and tables that may be associated with that plugin.

I would like point you guys to [Uninstall Methods](https://developer.wordpress.org/plugins/the-basics/uninstall-methods/) on Official WordPress Plugin Handbook. 

At this moment it's a less priority I think.

**Comment by wpsmith** [comment]
IMHO, **always** have an uninstall file. When someone _deactivates_ the plugin they no longer want to use it. When someone _deletes_ the plugin, they _really_ do not want it. Therefore, it is assumed by WordPress (remember decisions, not options) that the database will be cleaned for DB integrity. There is debate as to whether a developer should remove posts and post meta, but generally speaking those can remain. Regardless, all revisions (if post type supports revisions) and auto-save content should be deleted, if any exist.

Specifically for your plugin, your plugin sets options and should be deleted. Or as was mentioned by @mkrdip you can have a custom UNINSTALL admin page. Again the goal is database integrity and no orphaned options/data. In the least, all Kanban options should be set **not** to autoload. This may be a good stop gap action. And on activation, these options can be reset to autoload.

**Comment by wpsmith** [comment]
@mkrdip True, a description is valid, but this issue is fairly straight forward. There isn't an uninstall file. Most of the time, this is from ignorance or accident. The issue only serves that purpose.
